#### 2026.07.01

데이터 전처리

In [13]:
# 반정형 데이터 -> 정형 데이터
import re
import csv
import pandas as pd

# path
log_file_path = "./sample_logs.log"
output_csv_path = "./parsed_logs.csv"

# 정규 표현식패턴 정의
log_pattern = re.compile(
r'(?P<ip>\d+\.\d+\.\d+\.\d+)\s' # IP 주소
r'- - \[(?P<datetime>[^\]]+)\] ' # 날짜 및 시간
r'"(?P<method>GET|POST|PUT|DELETE|HEAD) ' # HTTP 메서드
r'(?P<path>[^ ]+).*?"\s' # 요청 경로
r'(?P<status>\d{3})\s' # 상태 코드
r'(?P<size>\d+)' # 응답 크기
)
# (?P<이름>패턴) 형태는"이름이있는 그룹" 으로, 추출 결과를딕셔너리처럼groupdict()로 관리할수 있게 해줍니다.

In [15]:
# 결과 리스트
parsed_logs = []

# 로그 파일의 각 행의 문자열을 확인하고 정규식에 따라 결과 추출
with open(log_file_path, 'r') as log_file:
    for line in log_file:
        match = log_pattern.search(line)
        if match:
            parsed_logs.append(match.groupdict())
        
print(parsed_logs)

# CSV 파일로 저장
with open(output_csv_path, 'w', newline='') as csv_file:
    fieldnames = ['ip', 'datetime', 'method', 'path', 'status', 'size']
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    for log in parsed_logs:
        writer.writerow(log)

print("보안 로그가 CSV 파일로 저장되었습니다:", output_csv_path)

[{'ip': '172.29.117.82', 'datetime': '14/Jun/2025:10:59:11 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '189'}, {'ip': '10.248.203.131', 'datetime': '14/Jun/2025:11:21:30 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '1024'}, {'ip': '172.25.180.188', 'datetime': '14/Jun/2025:11:55:08 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '2048'}, {'ip': '172.22.253.123', 'datetime': '14/Jun/2025:11:18:27 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '512'}, {'ip': '192.168.71.140', 'datetime': '14/Jun/2025:10:38:19 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '512'}, {'ip': '10.128.66.93', 'datetime': '14/Jun/2025:10:35:59 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '1024'}, {'ip': '192.168.75.62', 'datetime': '14/Jun/2025:10:38:37 +0900', 'method': 'GET', 'path': '/logout', 'status': '404', 'size': '1024'}, {'ip': '172.18.92.25', 'datetime': '14/Jun/2025:11:36:44 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '500', 'size': '2048'}, {'ip': '192.168.51.143', 'datetime': '14/Jun/2025:11:13:21 +0900', 'method': 'POST', 'path': '/submit', 'status': '200', 'size': '1024'}, {'ip': '172.22.139.20', 'datetime': '14/Jun/2025:11:58:29 +0900', 'method': 'POST', 'path': '/submit', 'status': '404', 'size': '2048'}, {'ip': '192.168.133.95', 'datetime': '14/Jun/2025:10:35:49 +0900', 'method': 'POST', 'path': '/api/data', 'status': '403', 'size': '189'}, {'ip': '10.7.48.121', 'datetime': '14/Jun/2025:11:00:31 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '532'}, {'ip': '10.204.50.153', 'datetime': '14/Jun/2025:11:52:48 +0900', 'method': 'GET', 'path': '/logout', 'status': '500', 'size': '512'}, {'ip': '192.168.0.149', 'datetime': '14/Jun/2025:11:25:50 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '512'}, {'ip': '192.168.170.144', 'datetime': '14/Jun/2025:11:34:26 +0900', 'method': 'GET', 'path': '/index.html', 'status': '404', 'size': '768'}, {'ip': '10.32.63.121', 'datetime': '14/Jun/2025:11:24:03 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '768'}, {'ip': '10.113.131.44', 'datetime': '14/Jun/2025:10:17:49 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '768'}, {'ip': '10.72.245.6', 'datetime': '14/Jun/2025:11:09:56 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '532'}, {'ip': '192.168.41.48', 'datetime': '14/Jun/2025:11:37:38 +0900', 'method': 'POST', 'path': '/api/data', 'status': '403', 'size': '189'}, {'ip': '172.31.168.60', 'datetime': '14/Jun/2025:10:49:07 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '512'}, {'ip': '10.149.9.214', 'datetime': '14/Jun/2025:10:29:47 +0900', 'method': 'POST', 'path': '/submit', 'status': '500', 'size': '512'}, {'ip': '192.168.170.94', 'datetime': '14/Jun/2025:10:06:53 +0900', 'method': 'POST', 'path': '/submit', 'status': '200', 'size': '512'}, {'ip': '192.168.147.71', 'datetime': '14/Jun/2025:11:59:37 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '512'}, {'ip': '172.28.81.28', 'datetime': '14/Jun/2025:10:31:26 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '2048'}, {'ip': '172.25.74.97', 'datetime': '14/Jun/2025:11:06:58 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '768'}, {'ip': '10.95.155.3', 'datetime': '14/Jun/2025:10:24:58 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '512'}, {'ip': '10.133.38.22', 'datetime': '14/Jun/2025:10:48:01 +0900', 'method': 'POST', 'path': '/api/data', 'status': '200', 'size': '1024'}, {'ip': '172.20.42.204', 'datetime': '14/Jun/2025:10:06:31 +0900', 'method': 'GET', 'path': '/logout', 'status': '404', 'size': '2048'}, {'ip': '10.41.22.78', 'datetime': '14/Jun/2025:10:59:14 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '2048'}, {'ip': '192.168.200.87', 'datetime': '14/Jun/2025:10:37:59 +0900', 'method': 'GET', 'path': '/logout', 'status': '404', 'size': '512'}, {'ip': '192.168.120.147', 'datetime': '14/Jun/2025:11:27:00 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '2048'}, {'ip': '10.214.190.164', 'datetime': '14/Jun/2025:10:03:08 +0900', 'method': 'POST', 'path': '/submit', 'status': '500', 'size': '532'}, {'ip': '192.168.252.61', 'datetime': '14/Jun/2025:11:12:37 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '1024'}, {'ip': '192.168.182.248', 'datetime': '14/Jun/2025:11:36:26 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '1024'}, {'ip': '10.59.15.31', 'datetime': '14/Jun/2025:11:30:20 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '2048'}, {'ip': '172.26.186.137', 'datetime': '14/Jun/2025:11:22:57 +0900', 'method': 'POST', 'path': '/submit', 'status': '404', 'size': '768'}, {'ip': '10.138.197.124', 'datetime': '14/Jun/2025:10:50:49 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '200', 'size': '512'}, {'ip': '10.190.126.172', 'datetime': '14/Jun/2025:11:09:49 +0900', 'method': 'GET', 'path': '/index.html', 'status': '500', 'size': '189'}, {'ip': '10.31.215.176', 'datetime': '14/Jun/2025:10:56:05 +0900', 'method': 'GET', 'path': '/logout', 'status': '500', 'size': '532'}, {'ip': '10.112.3.22', 'datetime': '14/Jun/2025:11:40:57 +0900', 'method': 'POST', 'path': '/api/data', 'status': '403', 'size': '512'}, {'ip': '10.37.226.235', 'datetime': '14/Jun/2025:11:47:24 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '532'}, {'ip': '10.96.133.198', 'datetime': '14/Jun/2025:10:22:29 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '200', 'size': '1024'}, {'ip': '192.168.61.72', 'datetime': '14/Jun/2025:10:00:59 +0900', 'method': 'POST', 'path': '/api/data', 'status': '200', 'size': '532'}, {'ip': '172.19.182.166', 'datetime': '14/Jun/2025:11:35:04 +0900', 'method': 'POST', 'path': '/submit', 'status': '200', 'size': '2048'}, {'ip': '10.99.161.108', 'datetime': '14/Jun/2025:10:24:47 +0900', 'method': 'GET', 'path': '/index.html', 'status': '404', 'size': '1024'}, {'ip': '10.245.94.29', 'datetime': '14/Jun/2025:11:42:25 +0900', 'method': 'POST', 'path': '/api/data', 'status': '404', 'size': '768'}, {'ip': '10.31.70.132', 'datetime': '14/Jun/2025:10:29:51 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '500', 'size': '2048'}, {'ip': '192.168.217.234', 'datetime': '14/Jun/2025:11:05:19 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '1024'}, {'ip': '192.168.133.20', 'datetime': '14/Jun/2025:11:21:28 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '1024'}, {'ip': '10.154.36.188', 'datetime': '14/Jun/2025:10:05:51 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '2048'}, {'ip': '172.17.244.15', 'datetime': '14/Jun/2025:10:36:28 +0900', 'method': 'POST', 'path': '/submit', 'status': '500', 'size': '2048'}, {'ip': '192.168.51.171', 'datetime': '14/Jun/2025:10:33:00 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '500', 'size': '2048'}, {'ip': '192.168.102.17', 'datetime': '14/Jun/2025:10:32:27 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '1024'}, {'ip': '172.31.12.2', 'datetime': '14/Jun/2025:11:16:46 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '512'}, {'ip': '192.168.104.37', 'datetime': '14/Jun/2025:10:06:40 +0900', 'method': 'POST', 'path': '/api/data', 'status': '404', 'size': '532'}, {'ip': '10.81.0.184', 'datetime': '14/Jun/2025:10:30:12 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '512'}, {'ip': '10.128.90.23', 'datetime': '14/Jun/2025:11:35:20 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '532'}, {'ip': '10.226.118.252', 'datetime': '14/Jun/2025:10:56:23 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '768'}, {'ip': '192.168.241.120', 'datetime': '14/Jun/2025:10:29:51 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '1024'}, {'ip': '192.168.159.117', 'datetime': '14/Jun/2025:11:09:22 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '189'}, {'ip': '192.168.128.122', 'datetime': '14/Jun/2025:10:23:24 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '768'}, {'ip': '10.6.94.13', 'datetime': '14/Jun/2025:10:33:00 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '1024'}, {'ip': '172.26.191.212', 'datetime': '14/Jun/2025:10:54:21 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '200', 'size': '2048'}, {'ip': '192.168.143.207', 'datetime': '14/Jun/2025:11:29:36 +0900', 'method': 'POST', 'path': '/api/data', 'status': '200', 'size': '189'}, {'ip': '10.246.178.10', 'datetime': '14/Jun/2025:10:04:01 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '768'}, {'ip': '172.27.126.147', 'datetime': '14/Jun/2025:11:46:23 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '532'}, {'ip': '192.168.67.194', 'datetime': '14/Jun/2025:10:42:28 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '404', 'size': '768'}, {'ip': '192.168.212.46', 'datetime': '14/Jun/2025:11:25:28 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '500', 'size': '532'}, {'ip': '192.168.98.118', 'datetime': '14/Jun/2025:10:48:22 +0900', 'method': 'GET', 'path': '/logout', 'status': '500', 'size': '2048'}, {'ip': '192.168.122.148', 'datetime': '14/Jun/2025:11:57:09 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '1024'}, {'ip': '10.193.222.40', 'datetime': '14/Jun/2025:11:57:41 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '189'}, {'ip': '192.168.212.45', 'datetime': '14/Jun/2025:11:31:32 +0900', 'method': 'GET', 'path': '/index.html', 'status': '404', 'size': '768'}, {'ip': '10.214.33.202', 'datetime': '14/Jun/2025:10:39:13 +0900', 'method': 'POST', 'path': '/submit', 'status': '403', 'size': '1024'}, {'ip': '192.168.84.211', 'datetime': '14/Jun/2025:11:43:49 +0900', 'method': 'GET', 'path': '/logout', 'status': '403', 'size': '768'}, {'ip': '172.21.11.196', 'datetime': '14/Jun/2025:11:53:20 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '532'}, {'ip': '172.31.151.174', 'datetime': '14/Jun/2025:11:08:37 +0900', 'method': 'POST', 'path': '/submit', 'status': '403', 'size': '1024'}, {'ip': '192.168.0.9', 'datetime': '14/Jun/2025:11:14:41 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '768'}, {'ip': '10.159.198.25', 'datetime': '14/Jun/2025:10:21:02 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '189'}, {'ip': '172.29.72.206', 'datetime': '14/Jun/2025:11:11:32 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '768'}, {'ip': '10.42.188.49', 'datetime': '14/Jun/2025:11:45:08 +0900', 'method': 'GET', 'path': '/index.html', 'status': '500', 'size': '1024'}, {'ip': '192.168.7.138', 'datetime': '14/Jun/2025:10:19:55 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '200', 'size': '768'}, {'ip': '172.29.92.9', 'datetime': '14/Jun/2025:11:55:58 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '1024'}, {'ip': '172.16.117.19', 'datetime': '14/Jun/2025:11:58:46 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '189'}, {'ip': '192.168.50.16', 'datetime': '14/Jun/2025:10:50:35 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '532'}, {'ip': '10.101.163.240', 'datetime': '14/Jun/2025:10:41:59 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '500', 'size': '2048'}, {'ip': '172.21.212.193', 'datetime': '14/Jun/2025:11:07:51 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '500', 'size': '768'}, {'ip': '10.203.27.194', 'datetime': '14/Jun/2025:11:40:18 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '532'}, {'ip': '192.168.140.167', 'datetime': '14/Jun/2025:10:46:50 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '500', 'size': '532'}, {'ip': '172.19.180.118', 'datetime': '14/Jun/2025:10:45:34 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '500', 'size': '1024'}, {'ip': '172.27.27.14', 'datetime': '14/Jun/2025:10:49:22 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '200', 'size': '532'}, {'ip': '10.142.139.187', 'datetime': '14/Jun/2025:11:54:29 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '512'}, {'ip': '10.105.86.49', 'datetime': '14/Jun/2025:10:59:14 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '512'}, {'ip': '192.168.161.34', 'datetime': '14/Jun/2025:10:19:53 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '512'}, {'ip': '172.17.88.25', 'datetime': '14/Jun/2025:11:35:30 +0900', 'method': 'GET', 'path': '/index.html', 'status': '200', 'size': '189'}, {'ip': '192.168.253.45', 'datetime': '14/Jun/2025:10:32:07 +0900', 'method': 'POST', 'path': '/api/data', 'status': '404', 'size': '2048'}, {'ip': '192.168.234.214', 'datetime': '14/Jun/2025:11:45:08 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '500', 'size': '189'}, {'ip': '192.168.91.72', 'datetime': '14/Jun/2025:10:16:00 +0900', 'method': 'GET', 'path': '/logout', 'status': '403', 'size': '189'}, {'ip': '10.149.2.154', 'datetime': '14/Jun/2025:10:26:13 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '500', 'size': '2048'}, {'ip': '10.138.241.117', 'datetime': '14/Jun/2025:11:52:00 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '532'}, {'ip': '172.27.192.29', 'datetime': '14/Jun/2025:10:24:57 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '1024'}, {'ip': '192.168.18.66', 'datetime': '14/Jun/2025:11:19:23 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '512'}, {'ip': '10.76.128.66', 'datetime': '14/Jun/2025:11:06:16 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '512'}, {'ip': '192.168.202.34', 'datetime': '14/Jun/2025:10:36:07 +0900', 'method': 'POST', 'path': '/api/data', 'status': '500', 'size': '2048'}, {'ip': '192.168.58.211', 'datetime': '14/Jun/2025:11:31:37 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '532'}, {'ip': '172.17.139.80', 'datetime': '14/Jun/2025:10:14:56 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '500', 'size': '512'}, {'ip': '172.18.68.130', 'datetime': '14/Jun/2025:11:23:37 +0900', 'method': 'GET', 'path': '/home.php', 'status': '500', 'size': '1024'}, {'ip': '172.26.131.61', 'datetime': '14/Jun/2025:10:18:20 +0900', 'method': 'POST', 'path': '/api/data', 'status': '403', 'size': '2048'}, {'ip': '172.19.46.73', 'datetime': '14/Jun/2025:11:50:24 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '2048'}, {'ip': '192.168.242.176', 'datetime': '14/Jun/2025:10:05:35 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '1024'}, {'ip': '172.26.255.49', 'datetime': '14/Jun/2025:10:33:37 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '189'}, {'ip': '10.254.215.15', 'datetime': '14/Jun/2025:11:06:16 +0900', 'method': 'POST', 'path': '/submit', 'status': '500', 'size': '2048'}, {'ip': '172.26.184.253', 'datetime': '14/Jun/2025:10:43:40 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '404', 'size': '2048'}, {'ip': '192.168.79.179', 'datetime': '14/Jun/2025:10:14:27 +0900', 'method': 'GET', 'path': '/index.html', 'status': '403', 'size': '189'}, {'ip': '10.192.74.227', 'datetime': '14/Jun/2025:11:07:25 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '404', 'size': '1024'}, {'ip': '192.168.43.89', 'datetime': '14/Jun/2025:10:45:18 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '768'}, {'ip': '10.31.79.220', 'datetime': '14/Jun/2025:10:40:54 +0900', 'method': 'GET', 'path': '/logout', 'status': '404', 'size': '2048'}, {'ip': '172.28.154.19', 'datetime': '14/Jun/2025:11:46:36 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '189'}, {'ip': '192.168.229.167', 'datetime': '14/Jun/2025:10:48:13 +0900', 'method': 'POST', 'path': '/api/data', 'status': '404', 'size': '512'}, {'ip': '172.22.243.189', 'datetime': '14/Jun/2025:11:08:48 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '532'}, {'ip': '172.23.11.94', 'datetime': '14/Jun/2025:10:04:35 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '403', 'size': '2048'}, {'ip': '172.21.84.161', 'datetime': '14/Jun/2025:10:08:59 +0900', 'method': 'GET', 'path': '/index.html', 'status': '404', 'size': '768'}, {'ip': '172.19.174.46', 'datetime': '14/Jun/2025:11:54:31 +0900', 'method': 'GET', 'path': '/logout', 'status': '404', 'size': '532'}, {'ip': '10.14.36.18', 'datetime': '14/Jun/2025:10:33:37 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '403', 'size': '768'}, {'ip': '192.168.103.67', 'datetime': '14/Jun/2025:10:12:14 +0900', 'method': 'GET', 'path': '/logout', 'status': '500', 'size': '512'}, {'ip': '10.131.81.77', 'datetime': '14/Jun/2025:11:40:27 +0900', 'method': 'GET', 'path': '/index.html', 'status': '500', 'size': '189'}, {'ip': '10.110.137.180', 'datetime': '14/Jun/2025:10:52:59 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '200', 'size': '768'}, {'ip': '192.168.101.92', 'datetime': '14/Jun/2025:10:14:42 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '404', 'size': '1024'}, {'ip': '172.20.215.187', 'datetime': '14/Jun/2025:10:47:28 +0900', 'method': 'GET', 'path': '/dashboard', 'status': '200', 'size': '768'}, {'ip': '10.249.206.54', 'datetime': '14/Jun/2025:11:50:17 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '768'}, {'ip': '10.216.178.196', 'datetime': '14/Jun/2025:10:16:08 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '768'}, {'ip': '192.168.165.25', 'datetime': '14/Jun/2025:11:00:41 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '200', 'size': '532'}, {'ip': '172.22.118.182', 'datetime': '14/Jun/2025:10:35:07 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '404', 'size': '768'}, {'ip': '192.168.112.3', 'datetime': '14/Jun/2025:10:22:13 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '1024'}, {'ip': '10.162.242.230', 'datetime': '14/Jun/2025:10:15:51 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '512'}, {'ip': '172.20.191.107', 'datetime': '14/Jun/2025:10:29:51 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '404', 'size': '1024'}, {'ip': '172.20.253.45', 'datetime': '14/Jun/2025:11:58:22 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '500', 'size': '532'}, {'ip': '172.31.13.198', 'datetime': '14/Jun/2025:10:25:34 +0900', 'method': 'GET', 'path': '/home.php', 'status': '200', 'size': '532'}, {'ip': '10.20.46.79', 'datetime': '14/Jun/2025:11:59:07 +0900', 'method': 'POST', 'path': '/submit', 'status': '500', 'size': '512'}, {'ip': '10.20.205.184', 'datetime': '14/Jun/2025:10:34:22 +0900', 'method': 'POST', 'path': '/submit', 'status': '403', 'size': '532'}, {'ip': '172.30.90.215', 'datetime': '14/Jun/2025:11:28:29 +0900', 'method': 'GET', 'path': '/admin/login.php', 'status': '403', 'size': '532'}, {'ip': '172.20.195.33', 'datetime': '14/Jun/2025:10:41:02 +0900', 'method': 'GET', 'path': '/home.php', 'status': '403', 'size': '1024'}, {'ip': '192.168.190.29', 'datetime': '14/Jun/2025:11:48:57 +0900', 'method': 'POST', 'path': '/upload.php', 'status': '500', 'size': '532'}, {'ip': '192.168.17.54', 'datetime': '14/Jun/2025:10:06:25 +0900', 'method': 'GET', 'path': '/home.php', 'status': '404', 'size': '532'}, {'ip': '192.168.39.24', 'datetime': '14/Jun/2025:11:12:54 +0900', 'me

In [ ]:
# 파일 로드
df = pd.read_csv('parsed_logs.csv')

In [18]:
df

,ip,datetime,method,path,status,size
0,172.29.117.82,14/Jun/2025:10:59:11 +0900,GET,/home.php,200,189
1,10.248.203.131,14/Jun/2025:11:21:30 +0900,GET,/admin/login.php,403,1024
2,172.25.180.188,14/Jun/2025:11:55:08 +0900,GET,/admin/login.php,404,2048
3,172.22.253.123,14/Jun/2025:11:18:27 +0900,GET,/dashboard,403,512
4,192.168.71.140,14/Jun/2025:10:38:19 +0900,GET,/admin/login.php,404,512
...,...,...,...,...,...,...
495,172.21.22.154,14/Jun/2025:10:59:51 +0900,GET,/index.html,404,1024
496,192.168.145.66,14/Jun/2025:11:55:58 +0900,GET,/logout,404,1024
497,192.168.188.143,14/Jun/2025:11:42:06 +0900,GET,/dashboard,200,768
498,172.27.113.162,14/Jun/2025:10:02:40 +0900,POST,/submit,403,1024
499,172.17.185.151,14/Jun/2025:11:25:39 +0900,POST,/submit,404,189

In [33]:
df_400 = df[df['status']//4 == 100]
df_400

,ip,datetime,method,path,status,size
1,10.248.203.131,14/Jun/2025:11:21:30 +0900,GET,/admin/login.php,403,1024
3,172.22.253.123,14/Jun/2025:11:18:27 +0900,GET,/dashboard,403,512
10,192.168.133.95,14/Jun/2025:10:35:49 +0900,POST,/api/data,403,189
17,10.72.245.6,14/Jun/2025:11:09:56 +0900,GET,/dashboard,403,532
18,192.168.41.48,14/Jun/2025:11:37:38 +0900,POST,/api/data,403,189
...,...,...,...,...,...,...
469,172.29.118.196,14/Jun/2025:11:36:35 +0900,POST,/api/data,403,1024
478,10.170.116.238,14/Jun/2025:11:45:43 +0900,POST,/upload.php,403,512
482,10.223.64.6,14/Jun/2025:10:46:13 +0900,GET,/home.php,403,512
490,192.168.24.241,14/Jun/2025:10:30:29 +0900,GET,/home.php,403,2048
498,172.27.113.162,14/Jun/2025:10:02:40 +0900,POST,/submit,403,1024

In [26]:
# path => /admin/...

df_admin = df[df['path'].str.startswith('/admin/')]
# df_admin = df[df['path'].str.re(r'^/admin/')] # 이 방법도 가능
df_admin

,ip,datetime,method,path,status,size
1,10.248.203.131,14/Jun/2025:11:21:30 +0900,GET,/admin/login.php,403,1024
2,172.25.180.188,14/Jun/2025:11:55:08 +0900,GET,/admin/login.php,404,2048
4,192.168.71.140,14/Jun/2025:10:38:19 +0900,GET,/admin/login.php,404,512
15,10.32.63.121,14/Jun/2025:11:24:03 +0900,GET,/admin/login.php,404,768
28,10.41.22.78,14/Jun/2025:10:59:14 +0900,GET,/admin/login.php,200,2048
...,...,...,...,...,...,...
452,10.63.41.199,14/Jun/2025:10:45:49 +0900,GET,/admin/login.php,404,1024
458,10.49.1.244,14/Jun/2025:10:06:23 +0900,GET,/admin/login.php,500,532
462,10.172.229.215,14/Jun/2025:10:35:40 +0900,GET,/admin/login.php,200,768
480,172.28.207.249,14/Jun/2025:10:51:43 +0900,GET,/admin/login.php,404,189
494,192.168.86.214,14/Jun/2025:10:38:34 +0900,GET,/admin/login.php,200,189

In [ ]:
# ip 집계 => Top 5
top_df_ip = df['ip'].value_counts().head(5)

ip
192.168.234.214    2
172.29.117.82      1
10.248.203.131     1
172.25.180.188     1
172.22.253.123     1
Name: count, dtype: int64

In [36]:
# 결측치 제거 예시 dropna()
import pandas as pd
# 데이터 프레임생성
data = {'Name': ['Alice', 'Bob', None],
'Age': [25, None, 30],
'Score': [85, 90, None]}
df = pd.DataFrame(data)
# 결측치가있는 행 제거
df_no_missing_rows = df.dropna()
print(df_no_missing_rows)
print('*'* 50)
# 결측치가 있는 열 제거
df_no_missing_cols = df.dropna(axis=1) # axis=1은 열을 기준으로 결측치 제거
print(df_no_missing_cols)

    Name   Age  Score
0  Alice  25.0   85.0
**************************************************
Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [39]:
# 결측치에 특정 값으로 대체
import pandas as pd
# 데이터 프레임생성
data = {'Name': ['Alice', 'Bob', None],
'Age': [25, None, 30],
'Score': [85, 90, None]}
df = pd.DataFrame(data)

df.fillna({'Name':'king', 'Age':20, 'Score':100})

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  20.0   90.0
2   king  30.0  100.0

In [ ]:
# IQR(Interquartile Range) 기반 이상치 처리
import numpy as np
# 이상치 처리
data = {'Scores': [70, 75, 80, 85, 90, 150]}
df = pd.DataFrame(data)

Q1 = df['Scores'].quantile(0.25)  # Q1
Q3 = df['Scores'].quantile(0.75)  # Q3
IQR = Q3 - Q1  # IQR 계산
#print(Q1, Q3, IQR)

low_bound = Q1 - 1.5 * IQR
high_bound = Q3 + 1.5 * IQR
#print(low_bound, high_bound)

#df_result = df[(df['Scores'] >= low_bound) & (df['Scores'] <= high_bound)]
# 이상치 데이터의 변경
df['Scores'] = df['Scores'].astype(float)  # 데이터 타입을 float으로 변환
df.loc[df['Scores'] < low_bound, 'Scores'] = low_bound
df.loc[df['Scores'] > high_bound, 'Scores'] = high_bound

   Scores
0    70.0
1    75.0
2    80.0
3    85.0
4    90.0
5   107.5

In [75]:
# 중복 데이터 처리 : 확인 -> 제거
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'Score': [85, 90, 85, 95, 90]
}
df = pd.DataFrame(data)
#df_dup = df.duplicated()  # 중복 여부 확인
#print(df.duplicated().sum())
#print(df.duplicated(subset=['Name']))
#print(df[df.duplicated()]) # 중복된 행 확인
df

#df_cleaned = df.drop_duplicates()
# df_cleaned

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [ ]:
df_cleaned1 = df.drop_duplicates(keep='last') # 중복 제거 인덱스 반대로
df_cleaned1

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [83]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

# 데이터 생성
data = pd.DataFrame({'Original': [50, 80, 90, 100, 60]})

# 표준화
scaler1 = StandardScaler()
data['scaled_1'] = scaler1.fit_transform(data[['Original']])

# 정규화
scaler2 = MinMaxScaler()
data['scaled_2'] = scaler2.fit_transform(data[['Original']])

data

   Original  scaled_1  scaled_2
0        50 -1.401826       0.0
1        80  0.215666       0.6
2        90  0.754829       0.8
3       100  1.293993       1.0
4        60 -0.862662       0.2

In [85]:
data = pd.DataFrame({'Fruits': ['사과', '배', '포도', '사과', '포도']})

encoder1 = LabelEncoder()
data['Label_Encoded'] = encoder1.fit_transform(data['Fruits'])
data

  Fruits  Label_Encoded
0     사과              1
1      배              0
2     포도              2
3     사과              1
4     포도              2

In [89]:
# sparse_output=False는 결과를 희소 행렬이 아닌 일반 배열로 반환하도록 설정하는 옵션입니다.
onehot_encoder = OneHotEncoder(sparse_output=False) 

onehot_encoded = onehot_encoder.fit_transform(data[['Label_Encoded']])
onehot_encoded

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
onehot_columns = onehot_encoder.get_feature_names_out()
onehot_df = pd.DataFrame(onehot_encoded, columns=onehot_columns)
print(onehot_columns)
print(onehot_df)

['Label_Encoded_0' 'Label_Encoded_1' 'Label_Encoded_2']
   Label_Encoded_0  Label_Encoded_1  Label_Encoded_2
0              0.0              1.0              0.0
1              1.0              0.0              0.0
2              0.0              0.0              1.0
3              0.0              1.0              0.0
4              0.0              0.0              1.0

In [ ]:
# axis=1은 열 방향으로 결합을 의미합니다. 즉, 기존 데이터프레임(data)과 
# 원-핫 인코딩된 데이터프레임(onehot_df)을 열 단위로 합쳐서 
# 새로운 데이터프레임(result_df)을 생성합니다.
result_df = pd.concat([data, onehot_df], axis=1)
result_df

  Fruits  Label_Encoded  Label_Encoded_0  Label_Encoded_1  Label_Encoded_2
0     사과              1              0.0              1.0              0.0
1      배              0              1.0              0.0              0.0
2     포도              2              0.0              0.0              1.0
3     사과              1              0.0              1.0              0.0
4     포도              2              0.0              0.0              1.0